service: dev-secret

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# o serverless-offline é um modulo que é um plugin do fremework serverless
# quando utilizamos plugins no serverless temos que declarar os plugins dentro
# do arquivo serverless.yml
plugins:
  - serverless-offline

functions:
  create:
    handler: src/handlers/secrets.create

    # para disparar uma função é preciso criar um evento. Como vai essa função 
    # vai ser disparada atrvés de uma rota HTTP é só criar um evento HTTP
    events:
      - http:
          path: /secret/
          method: POST
          cors: true

  get:
    handler: src/handlers/secrets.get
    events:
      - http:
          path: /secret/{id}
          method: GET
          cors: true

  draw:
    handler: src/handlers/secrets.draw
    events:
      - http:
          path: /secret/{id}/draw
          method: PUT
          cors: true
